### ISSUE TITLE
Compilation error in VisualStudio 2017

### ISSUE THREAD

**Issue by riku22** [anthonyheddings/OfficeKeyFix#1]
Hello.
I tried to compile "OfficeKeyFix.cpp" with the following command in VisualStudio2017 on Windows10.

    cl /EHsc OfficeKeyFix.cpp

However, compilation fails with the following error.

    /out:OfficeKeyFix.exe
    OfficeKeyFix.obj
    OfficeKeyFix.obj: error LNK2019: Unresolved external symbol __imp__RegisterHotKey @ 16 was referenced in function _main.
    OfficeKeyFix.obj: error LNK2019: Unresolved external symbol __imp__UnregisterHotKey @ 8 was referenced in function _main.
    OfficeKeyFix.exe: fatal error LNK1120: 2 outstanding external references

I'm in trouble because I don't know C ++ at all.
How can I resolve this error?
Also, what version of VisualStudio can be compiled?
I would appreciate it if you could tell me.
Best regards.

**Comment by greggman** [comment]
I put a compiled version here

https://github.com/greggman/OfficeKeyFix/releases/tag/exe

If you want to compile it yourself install Visual Studio (it's free). Then launch Visual Studio

Pick "Create New Project"

![vs-step-01](https://user-images.githubusercontent.com/234804/78658996-e317b300-7905-11ea-8fb9-7574a83e628f.jpg)

Pick "Empty Project C++"

![vs-step-02](https://user-images.githubusercontent.com/234804/78658999-e448e000-7905-11ea-9552-df47e6e12962.jpg)

Choose a location and pick create

![vs-step-03](https://user-images.githubusercontent.com/234804/78659001-e448e000-7905-11ea-93a7-c947db633b5a.jpg)

In the "Solution Explorer" right click "Source Files", Pick Add->Exsiting Item. Then select the OfficeKeyFix.cpp file you downloaded 

![vs-step-04](https://user-images.githubusercontent.com/234804/78659004-e4e17680-7905-11ea-880a-9d476b3ef30e.jpg)

Where it says "Debug" in the toolbar click the dropdown and switch to "Release"

![vs-step-05](https://user-images.githubusercontent.com/234804/78659006-e57a0d00-7905-11ea-831c-74b1a8d5d9d1.jpg)

Then from the Build menu pick "Build Solution"

![vs-step-06](https://user-images.githubusercontent.com/234804/78659008-e57a0d00-7905-11ea-9d61-9a9db1d2adf3.jpg)

The exe will be placed in the project folder under "Release". In the example above that would be "C:\Users\gregg\temp\Project1\Release\Project1.exe"

I'm sure there is a way to do this from the command line without all these steps but several minutes of searching didn't bring up any results so .... ¯\_(ツ)_/¯.

**Comment by riku22** [comment]
I compiled it using the method you taught me, and it was successful.
Thank you very much.
Sincerely yours.
